# scripts/auto_pr.py
import os
import subprocess
import requests
from dotenv import load_dotenv

load_dotenv()

REPO = "ianlucas1/agent_platform"
BASE_BRANCH = "main"
TOKEN = os.environ["GITHUB_PERSONAL_ACCESS_TOKEN"]

def get_current_branch():
    return subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).decode().strip()

def push_branch(branch):
    subprocess.run(["git", "push", "--set-upstream", "origin", branch], check=True)  # nosec B603,B607

def open_pull_request(branch):
    url = f"https://api.github.com/repos/ianlucas1/agent_platform/pulls"
    headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json"
}
    data = {
        "title": f"[{branch}] Agent-generated PR",
        "head": branch,
        "base": BASE_BRANCH,
        "body": "Autogenerated PR for task completion. Debrief report pending."
    }
    resp = requests.post(url, headers=headers, json=data, timeout=10)
    resp.raise_for_status()
    print(f"✅ PR created: {resp.json()['html_url']}")

if __name__ == "__main__":
    branch = get_current_branch()
    # FS21: generate debrief report before opening the PR
    subprocess.run(["python3", "scripts/generate_debrief.py"], check=True)  # nosec B603
    push_branch(branch)
    open_pull_request(branch)
    # trigger CI
